name: "Docker Tests"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/LICENSE.txt'
jobs:
  ci:
    name: Docker Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test building container
      run: make docker-build VERSION=ci
      env:
        ACCESS_KEY: ${{ secrets.CI_AWS_ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.CI_AWS_SECRET_KEY }}
    
    - name: Run compose
      run: make docker-tests
      
    - name: Cleanup
      run: make docker-cleanup VERSION=ci