name: "Tests"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  ci:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        language: [ 'go' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.6'

    - name: Run Go Vet
      run: go vet -race ./cmd/retriever

      # The app has to be compiled with cgo enabled
    - name: Run Go Build
      run: go build -o retriever ./cmd/retriever
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0

    - name: Run integration tests
      run: make integration-tests && make cleanup
      env:
        AWS_REGION: "us-east-2"
        AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_KEY }}

    - name: Test building container
      run: make docker-build VERSION=ci && make docker-cleanup VERSION=ci